//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGDIEM
    {
        public int Id { get; set; }
        public Nullable<int> Id_HocKy { get; set; }
        public Nullable<int> Id_Nam { get; set; }
        public Nullable<int> Id_Mon { get; set; }
        public Nullable<int> Id_Khoa { get; set; }
        public Nullable<int> Id_Lop { get; set; }
        public Nullable<int> Id_LanHoc { get; set; }
        public string UrlFile { get; set; }
    
        public virtual HOCKY HOCKY { get; set; }
        public virtual KHOA KHOA { get; set; }
        public virtual LANHOC LANHOC { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
